'use client';
import {motion,useReducedMotion} from 'framer-motion';
import {useRef,useState} from 'react';
import {X,GraduationCap} from 'lucide-react';
export interface PathStation {id:string;title:string;hours:number;courses?:{code:string;name?:string|null;hours:number}[];}
export function Station({station,index,x,y,onSelect}:{station:PathStation;index:number;x:number;y:number;onSelect:()=>void}){return <g className="map-station" tabIndex={0} role="button" aria-label={`${station.title}، ${station.hours} ساعة`} onClick={onSelect} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect();}}} transform={`translate(${x} ${y})`}><circle r="29" fill="#0f1a17" stroke="#c9a45c" strokeOpacity=".4"/><circle r="21" fill={index===0?'#0e5a4f':'#14241d'} stroke="#d9884a"/><text y="6" fill="#f3e9d8" fontSize="16" textAnchor="middle">{index+1}</text><text y="57" fill="#f3e9d8" fontSize="14" textAnchor="middle">{station.title}</text><text y="80" fill="#aebcb3" fontSize="12" textAnchor="middle">{station.hours} ساعة</text>{station.courses?.slice(0,3).map((c,i)=><circle key={c.code} cx={(i-1)*9} cy="-39" r="2" fill="#d9884a"/>)}</g>;}
export function PathMap({stations,caption='رحلة التخرج'}:{stations:PathStation[];caption?:string}){
 const [selected,setSelected]=useState<PathStation|null>(null);const dialog=useRef<HTMLDialogElement>(null);const reduced=useReducedMotion();
 const open=(s:PathStation)=>{setSelected(s);dialog.current?.showModal();};
 function renderMap(vertical:boolean){const width=vertical?320:1000;const height=vertical?Math.max(360,stations.length*160+150):Math.max(400,Math.ceil(stations.length/4)*230+120);const points=stations.map((_,i)=>vertical?{x:i%2?110:210,y:80+i*160}:{x:Math.floor(i/4)%2?140+(i%4)*240:860-(i%4)*240,y:100+Math.floor(i/4)*230+(i%2)*35});const d=points.map((p,i)=>i===0?`M${p.x} ${p.y}`:`C${points[i-1].x} ${(points[i-1].y+p.y)/2+60},${p.x} ${(points[i-1].y+p.y)/2-60},${p.x} ${p.y}`).join(' ');
 return <svg className={vertical?'journey-svg journey-mobile':'journey-svg journey-desktop'} viewBox={`0 0 ${width} ${height}`} aria-label={caption}><defs><pattern id={vertical?'map-dots-m':'map-dots-d'} width="44" height="44" patternUnits="userSpaceOnUse"><circle cx="22" cy="22" r=".8" fill="#c9a45c" opacity=".2"/></pattern></defs><rect width={width} height={height} fill={`url(#${vertical?'map-dots-m':'map-dots-d'})`}/><path d={`M0 ${height-75}Q${width/3} ${height-160} ${width} ${height-25}V${height}H0Z`} fill="#14261c"/><path d={d} stroke="#d9884a" strokeOpacity=".08" strokeWidth="16" fill="none"/><motion.path d={d} stroke="#c9a45c" strokeWidth="1.5" fill="none" initial={reduced?false:{pathLength:0}} animate={{pathLength:1}} transition={{duration:1.2,ease:'easeOut'}}/>{stations.map((s,i)=><Station key={s.id} station={s} index={i} {...points[i]} onSelect={()=>open(s)}/>)}<text x={width/2} y={height-25} textAnchor="middle" fill="#d9884a" fontSize="12">نحو التخرج</text></svg>;}
 return <div className="journey-map engraved">{renderMap(false)}{renderMap(true)}<dialog ref={dialog} className="detail-sheet" onClose={()=>setSelected(null)}><div className="flex items-center justify-between gap-4"><h2>{selected?.title}</h2><button autoFocus className="icon-button" aria-label="إغلاق التفاصيل" onClick={()=>dialog.current?.close()}><X size={18}/></button></div>{selected&&<><div className="sheet-hours"><GraduationCap size={28}/><strong>{selected.hours}</strong><span>ساعة</span></div>{selected.courses?.length?<ul className="sheet-courses">{selected.courses.map(c=><li key={c.code}><div><strong>{c.name||c.code}</strong><code>{c.code}</code></div><span>{c.hours} س</span></li>)}</ul>:null}</>}</dialog></div>;
}
